config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#top'
  get 'books' => 'books#index', as: 'index_book'
  get 'books/:id' => 'books#show', as: 'book'
  post 'books' => 'books#create'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully created." 
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully updated." 
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
    flash[:notice] = "Book was successfully destroyed." 
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>    
  </ul>
<% end %>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Body</p>
  <%= f.text_area :body %>
  <p><%= f.submit 'Update Book' %></p>
<% end %>
<p>
  <%= link_to "Show", book_path(@book.id) %>|
  <%= link_to "Back", books_path %>
</p>

app/views/books/index.html.erb
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
<h1><strong>Books</strong></h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th> <!-- 詳細ページへのリンク -->
      <th></th> <!-- 編集ページへのリンク -->
      <th></th> <!-- 削除ボタン -->
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td>
        <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>New Book</h2>
  <% if @book.errors.any? %>
    <%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </ul>
  <% end %>
  <%= form_with model:@book, url:'/books', local:true do |f| %>
    <p>Title</p>
    <%= f.text_field :title %>
    <p>Body</p>
    <%= f.text_area :body %>
    <p><%= f.submit 'Create Book' %></p>
  <% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>
<h3>Title:</h3>
<p><%= @book.title %></p>
<h3>Body:</h3>
<p><%= @book.body %></p>
<p>
  <%= link_to "Edit", edit_book_path(@book.id) %>|
  <%= link_to "Back", books_path %>
</p>

app/views/books/top.html.erb
<h1>ようこそBookersへ！</h1>
<p>
  <strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
</p>
<p>
  印象を共有し交換することができます
</p>

<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>